package com.guohanlin.model

data class InterfaceDetailInfoData(
    val __v: Int,
    val _id: Int,
    val add_time: Int,
    val api_opened: Boolean,
    val catid: Int,
    val desc: String,
    val edit_uid: Int,
    val index: Int,
    val method: String,
    val path: String,
    val project_id: Int,
    val query_path: QueryPath,
    val req_body_form: List<Any>,
    val req_body_is_json_schema: Boolean,
    val req_body_other: String,
    val req_body_type: String,
    val req_headers: List<ReqHeader>,
    val req_params: List<Any>,
    val req_query: List<Any>,
    val res_body: String,
    val res_body_is_json_schema: Boolean,
    val res_body_type: String,
    val status: String,
    val tag: List<Any>,
    val title: String,
    val type: String,
    val uid: Int,
    val up_time: Int,
    val username: String
)